# Generated by Django 4.2 on 2025-05-31 09:04

from django.db import migrations, models
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=300, verbose_name='Заголовок на русском')),
                ('title_kz', models.CharField(max_length=300, verbose_name='Заголовок на казахском')),
                ('title_en', models.CharField(max_length=300, verbose_name='Заголовок на английском')),
                ('image', models.FileField(upload_to='news/pictures/', verbose_name='Основная картинка новости')),
                ('small_description_ru', models.CharField(max_length=300, verbose_name='Текст превью на русском')),
                ('small_description_kz', models.CharField(max_length=300, verbose_name='Текст превью на казахском')),
                ('small_description_en', models.CharField(max_length=300, verbose_name='Текст превью на английском')),
                ('content_ru', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Контент на русском')),
                ('content_kz', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Контент на казахском')),
                ('content_en', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Контент на английском')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показать?')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикаций')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
