# Generated by Django 4.2 on 2025-05-31 09:19

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_news_small_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Контент на английском'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_kz',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Контент на казахском'),
        ),
    ]
