# Generated by Django 4.2 on 2025-05-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_news_content_en_alter_news_content_kz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='Ключ')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название на русском')),
                ('name_kz', models.CharField(max_length=100, verbose_name='Название на казахском')),
                ('name_en', models.CharField(max_length=100, verbose_name='Название на английском')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(related_name='news', to='common.tag', verbose_name='Теги'),
        ),
    ]
