# Generated by Django 4.2 on 2025-05-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_news_banner_image_news_show_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Название (RU)')),
                ('title_kz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (KZ)')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название (EN)')),
                ('location_ru', models.CharField(max_length=255, verbose_name='Место проведения (RU)')),
                ('location_kz', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место проведения (KZ)')),
                ('location_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место проведения (EN)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Описание (RU)')),
                ('description_kz', models.TextField(blank=True, null=True, verbose_name='Описание (KZ)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Описание (EN)')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время проведения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['-datetime'],
            },
        ),
    ]
