# Generated by Django 4.2 on 2025-05-31 14:22

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание (EN)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_kz',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание (KZ)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_ru',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Описание (RU)'),
        ),
    ]
