# Generated by Django 4.2 on 2025-05-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('text_ru', models.TextField(db_index=True, unique=True, verbose_name='Текст на языке: Русский')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Текст на языке: English')),
                ('text_kk', models.TextField(blank=True, null=True, verbose_name='Текст на языке: Kazakh')),
            ],
            options={
                'verbose_name': 'Перевод',
                'verbose_name_plural': 'Переводы',
            },
        ),
    ]
