# Generated by Django 4.2 on 2025-05-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='text_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Текст на языке: Қазақша'),
        ),
    ]
